name: Saludo

on: [push]

jobs:
  saludo:
    runs-on: ubuntu-latest

    steps:
    - name: Saludo
      run: echo "Hola, mundo!"

  other:
    runs-on: ubuntu-latest

    steps:
    - name: Listado
      run: ls -al
        